// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvT8T0PvtyFuHiP7TMPzLBmul1iCPVoks',
    appId: '1:352372478573:web:cf672aee6a441de2902564',
    messagingSenderId: '352372478573',
    projectId: 'pluse-exchange',
    authDomain: 'pluse-exchange.firebaseapp.com',
    storageBucket: 'pluse-exchange.firebasestorage.app',
    measurementId: 'G-W1FQX6EM6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmOGk-M8YBAfyF7l6xHGcIIfiCwjsHs3Y',
    appId: '1:352372478573:android:6c76c3fa2a726137902564',
    messagingSenderId: '352372478573',
    projectId: 'pluse-exchange',
    storageBucket: 'pluse-exchange.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJu7LHxRpLF0qYLH2_WXE_CV1-iIwb3Cg',
    appId: '1:352372478573:ios:02711e5cd65b3924902564',
    messagingSenderId: '352372478573',
    projectId: 'pluse-exchange',
    storageBucket: 'pluse-exchange.firebasestorage.app',
    androidClientId: '352372478573-fhqtrs3no8ffoiuns9u0lpvqi11stkkm.apps.googleusercontent.com',
    iosClientId: '352372478573-l3n889friulhrp1uefp42fdd5qkn9081.apps.googleusercontent.com',
    iosBundleId: 'com.example.pluseExchange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJu7LHxRpLF0qYLH2_WXE_CV1-iIwb3Cg',
    appId: '1:352372478573:ios:02711e5cd65b3924902564',
    messagingSenderId: '352372478573',
    projectId: 'pluse-exchange',
    storageBucket: 'pluse-exchange.firebasestorage.app',
    androidClientId: '352372478573-fhqtrs3no8ffoiuns9u0lpvqi11stkkm.apps.googleusercontent.com',
    iosClientId: '352372478573-l3n889friulhrp1uefp42fdd5qkn9081.apps.googleusercontent.com',
    iosBundleId: 'com.example.pluseExchange',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvT8T0PvtyFuHiP7TMPzLBmul1iCPVoks',
    appId: '1:352372478573:web:1929becfed21cc95902564',
    messagingSenderId: '352372478573',
    projectId: 'pluse-exchange',
    authDomain: 'pluse-exchange.firebaseapp.com',
    storageBucket: 'pluse-exchange.firebasestorage.app',
    measurementId: 'G-0FTQPSYK7Q',
  );
}
